#207 [feat] 글쓰기 언급링크 기능
Eagle-Strike-7/stelligence-frontend pull request #243
Opened 2024-02-15 22:26 UTC by moonjw0

## 변경 내용

- 언급링크 연결 버튼 구현
- 언급링크 마크다운 구현

## 특이 사항

- 현재 마크다운을 통한 언급링크 기능이 제대로 동작하지 않습니다
- 코드 질문 및 공유를 위해 PR에 포함했습니다

## 체크리스트

-   [x] PR 날리기 전에 develop branch pull 받으셨나요?
-   [x] 다른 담당자 파일을 수정한 부분에 대해서 이야기 하셨나요?
-   [x] 주석 Comment Anchors 컨벤션에 맞추어 다셨나요?

2024-02-16 15:46 UTC, naringst requested changes
정말 고생 많으셨습니다!!!

2024-02-16 15:46 UTC, naringst commented on src/components/Common/Star/StarContentInput/MentionLink.ts
p1(오류해결제안): 공백과 엔터에서 링크 인덱스 문제인 것 같습니다. doc에서 텍스트를 추출했을 때 문자열 공백/엔터 인덱스 계산과 addMark함수에서(에디터 계산) 차이나는 게 원인이라고 생각됩니다. 공백은 하나 당겨져서 링크가 들어가니 인덱스를 하나 뒤로 밀어주면 될 것 같고, 엔터는 태그 이전 \n의 개수를 세어 인덱스 위치를 옮겨주면 될 것 같습니다!!

2024-02-16 15:50 UTC, LeeDahee23 approved these changes
두 분 다 너무 고생많으셨습니다!!🥹👍

2024-02-17 16:35 UTC, merged

2024-02-17 16:35 UTC, moonjw0 commented on src/components/Common/Star/StarContentInput/MentionLink.ts
감사합니다~! 수정완료했습니다!